/// <reference types="vite/client" />
declare module "three"
declare module "dat.gui"
declare module "@gdmp/three-scene-editor"
declare module "proj4"
declare module "echarts"
declare module "three/addons/postprocessing/OutputPass.js"
declare module "three/addons/postprocessing/EffectComposer.js"
declare module "three/addons/postprocessing/SSRPass.js"
declare module "three/addons/controls/OrbitControls.js"
declare module "three/addons/postprocessing/ShaderPass.js"
declare module "three-editor-cores"